export type FamiliaProfesionalOption = {
  value: string;
  label: string;
  adzunaCategory: string | null;
};

export const FAMILIAS_PROFESIONALES: FamiliaProfesionalOption[] = [
  { value: 'Informática y comunicaciones', label: 'Informática y comunicaciones', adzunaCategory: 'it-jobs' },
  { value: 'Administración y gestión', label: 'Administración y gestión', adzunaCategory: 'admin-jobs' },
  { value: 'Comercio y marketing', label: 'Comercio y marketing', adzunaCategory: 'pr-advertising-marketing-jobs' },
  { value: 'Sanidad', label: 'Sanidad', adzunaCategory: 'healthcare-nursing-jobs' },
  { value: 'Hostelería y turismo', label: 'Hostelería y turismo', adzunaCategory: 'hospitality-catering-jobs' },
  { value: 'Servicios socioculturales y a la comunidad', label: 'Servicios socioculturales y a la comunidad', adzunaCategory: 'social-work-jobs' },
  { value: 'Imagen y sonido', label: 'Imagen y sonido', adzunaCategory: 'creative-design-jobs' },
  { value: 'Edificación y obra civil', label: 'Edificación y obra civil', adzunaCategory: 'trade-construction-jobs' },
  { value: 'Electricidad y electrónica', label: 'Electricidad y electrónica', adzunaCategory: 'engineering-jobs' },
  { value: 'Energía y agua', label: 'Energía y agua', adzunaCategory: 'energy-oil-gas-jobs' },
  { value: 'Fabricación mecánica', label: 'Fabricación mecánica', adzunaCategory: 'manufacturing-jobs' },
  { value: 'Industrias alimentarias', label: 'Industrias alimentarias', adzunaCategory: 'manufacturing-jobs' },
  { value: 'Instalación y mantenimiento', label: 'Instalación y mantenimiento', adzunaCategory: 'maintenance-jobs' },
  { value: 'Química', label: 'Química', adzunaCategory: 'scientific-qa-jobs' },
  { value: 'Transporte y mantenimiento de vehículos', label: 'Transporte y mantenimiento de vehículos', adzunaCategory: 'logistics-warehouse-jobs' },
  { value: 'Actividades físicas y deportivas', label: 'Actividades físicas y deportivas', adzunaCategory: null },
  { value: 'Agraria', label: 'Agraria', adzunaCategory: null },
  { value: 'Artes gráficas', label: 'Artes gráficas', adzunaCategory: 'creative-design-jobs' },
];

export const LOCALIDADES_ES: string[] = [
  'A Coruña',
  'Alicante',
  'Almería',
  'Badajoz',
  'Barcelona',
  'Bilbao',
  'Burgos',
  'Cáceres',
  'Cádiz',
  'Castellón',
  'Ciudad Real',
  'Córdoba',
  'Cuenca',
  'Donostia / San Sebastián',
  'Gijón',
  'Girona',
  'Granada',
  'Guadalajara',
  'Huelva',
  'Huesca',
  'Jaén',
  'Las Palmas de Gran Canaria',
  'León',
  'Lleida',
  'Logroño',
  'Lugo',
  'Madrid',
  'Málaga',
  'Murcia',
  'Ourense',
  'Oviedo',
  'Palencia',
  'Palma',
  'Pamplona',
  'Pontevedra',
  'Salamanca',
  'Santa Cruz de Tenerife',
  'Santander',
  'Segovia',
  'Sevilla',
  'Soria',
  'Tarragona',
  'Teruel',
  'Toledo',
  'Valencia',
  'Valladolid',
  'Vigo',
  'Vitoria-Gasteiz',
  'Zamora',
  'Zaragoza',
];

export const LOCALIDAD_TO_COMUNIDAD: Record<string, string> = {
  'A Coruña': 'Galicia',
  'Alicante': 'Comunidad Valenciana',
  'Almería': 'Andalucía',
  'Badajoz': 'Extremadura',
  'Barcelona': 'Cataluña',
  'Bilbao': 'País Vasco',
  'Burgos': 'Castilla y León',
  'Cáceres': 'Extremadura',
  'Cádiz': 'Andalucía',
  'Castellón': 'Comunidad Valenciana',
  'Ciudad Real': 'Castilla-La Mancha',
  'Córdoba': 'Andalucía',
  'Cuenca': 'Castilla-La Mancha',
  'Donostia / San Sebastián': 'País Vasco',
  'Gijón': 'Asturias',
  'Girona': 'Cataluña',
  'Granada': 'Andalucía',
  'Guadalajara': 'Castilla-La Mancha',
  'Huelva': 'Andalucía',
  'Huesca': 'Aragón',
  'Jaén': 'Andalucía',
  'Las Palmas de Gran Canaria': 'Canarias',
  'León': 'Castilla y León',
  'Lleida': 'Cataluña',
  'Logroño': 'La Rioja',
  'Lugo': 'Galicia',
  'Madrid': 'Comunidad de Madrid',
  'Málaga': 'Andalucía',
  'Murcia': 'Región de Murcia',
  'Ourense': 'Galicia',
  'Oviedo': 'Asturias',
  'Palencia': 'Castilla y León',
  'Palma': 'Islas Baleares',
  'Pamplona': 'Navarra',
  'Pontevedra': 'Galicia',
  'Salamanca': 'Castilla y León',
  'Santa Cruz de Tenerife': 'Canarias',
  'Santander': 'Cantabria',
  'Segovia': 'Castilla y León',
  'Sevilla': 'Andalucía',
  'Soria': 'Castilla y León',
  'Tarragona': 'Cataluña',
  'Teruel': 'Aragón',
  'Toledo': 'Castilla-La Mancha',
  'Valencia': 'Comunidad Valenciana',
  'Valladolid': 'Castilla y León',
  'Vigo': 'Galicia',
  'Vitoria-Gasteiz': 'País Vasco',
  'Zamora': 'Castilla y León',
  'Zaragoza': 'Aragón',
};
