package com.fctnow.backend.notificaciones;

public enum NotificacionTipo {
  RECOMENDACION,
  SOLICITUD_RECIBIDA,
  SOLICITUD_ACEPTADA,
  SOLICITUD_RECHAZADA,
  SOLICITUD_ACEPTADA_PENDIENTE_ASIGNACION,
  ASIGNACION_CREADA,
  OFERTA_PUBLICADA,
  OFERTA_MODIFICADA,
  DOCUMENTACION_PENDIENTE,
  SEGUIMIENTO_PENDIENTE,
  EVALUACION_PENDIENTE,
  INCIDENCIA_REGISTRADA
}
